### ISSUE TITLE
Unnecessary memory limits setting

### ISSUE THREAD

**Issue by kaiiiz** [terratrax/nextcloud-multimedia#2]
Hi, I noticed that you added 2GB memory limit setting in:

https://github.com/terratrax/nextcloud-multimedia/blob/0cc51ec2588b41f02a49d4dd71311453d276130a/Dockerfile#L78

However, I found that the php `memory_limits` setting is actually `512M` after the container is started.

After doing some research, I notice that `/usr/local/etc/php/conf.d/nextcloud.ini` has the following settings:

```
memory_limit=${PHP_MEMORY_LIMIT}
upload_max_filesize=${PHP_UPLOAD_LIMIT}
post_max_size=${PHP_UPLOAD_LIMIT}
```

and the `PHP_MEMORY_LIMIT` is `512M` by default.

I set `PHP_MEMORY_LIMIT=4G` in the docker environment, and the PHP memory_limits setting is correctly set to 4G, as expected. Therefore, I think the additional memory limit setting in `memory-limit.ini` is unnecessary and can be removed.

**Comment by terratrax** [comment]
Hello.  The setting in /usr/local/etc/php/conf.d/memory-limit.in is what sets PHP_MEMORY_LIMIT.  Since it is by default 512MB, some of the facial recognition modules will not run which is why this line exists.

You can also override the amount through the environment variable as you found, but if you don't do that and the Dockerfile line isn't there, it wont run.

**Comment by kaiiiz** [comment]
The problem I met is that the `memory_limit=2048M` setting in `/usr/local/etc/php/conf.d/memory-limit.ini` is not effective since it's overridden by the `memory_limit` setting in `/usr/local/etc/php/conf.d/nextcloud.ini` by default.

I think this is because the configuration is loaded alphanumerically, so the setting in `nextcloud.ini` will override the setting in `memory-limit.ini`.

**Comment by terratrax** [comment]
If you set the environment variable then you are right it is not necessary.  The line is there in the case you **don't** set the environment variable; to replace the default value of 512M with 2048M.

**Comment by terratrax** [comment]
The memory limit is set in the memory-limit.ini as a backstop/minimum to avoid a OOM crash.  Adding a larger value the nextcloud.ini will override the value (this is intended and recommended).
